config/routes.rb
Brocks::Application.routes.draw do


  root "pins#busca"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "pins/perfil", to: "pins#perfil", as: "perfil"
  get "pins/busca", to: "pins#busca", as: "busca"
  get "pins/oridomi", to: "pins#oridomi", as: "oridomi"
  post "pins/busca", to: "pins#busca", as: "novo"
  post "pins/index", to: "pins#index", as: "cenas"
  post "pins/perfil", to: "pins#perfil", as: "buscacomquery"
  get "pins/fromlink", to: "pins#fromlink", as: "sacaimagemdolinkget"    
  post "pins/fromlink", to: "pins#fromlink", as: "sacaimagemdolinkpost"
  

  devise_for :users
  
  namespace :admin do
    root "pins#busca"
    resources :users
    
  end
  
end


Rails.application.routes.draw do
  resources :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	mount_uploader :slyce, SlyceUploader
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  
  def index
    #vai buscar as infos do user atraves do username
    @teste = Instagram.user_search(params[:q], {:count => 1})
    #saca apenas o user id dessas infos
    @teste = @teste.first.id
    #vai buscar as ultimas 20 fotos desse userid
    @instagram = Instagram.user_recent_media(@teste, {:count => 20})
  end

  def perfil
    @instagram = Instagram.user_search(params[:q], {:count => 1})
  end

  def fromlink
    require "net/http"
    require 'RMagick'


    #saca so o fim do url da foto que o user colou, para usar no pedido do oembed
    @short = URI(params[:q]).path.split('/').last
    @pissa = URI(params[:p]).path.split('/').last

    #junta tudo para ter o url directo da foto com tamanho grande
    @short = 'https://instagram.com/p/' + @short + '/media/?size=l'
    @pissa = 'https://instagram.com/p/' + @pissa + '/media/?size=l'

    #CORTA AS FATIAS DA PRIMEIRA IMAGEM E GUARDA-A NO DISCO
    for i in 0..3
      @image = MiniMagick::Image.open(@short)
      @image.crop("160x640+#{i * 160}+0")
      @image.write "app/assets/images/cone" + i.to_s() + ".png"
    end

    #CORTA AS FATIAS DA SEGUNDA IMAGEM E GUARDA-A NO DISCO
    for i in 0..3
      @image = MiniMagick::Image.open(@pissa)
      @image.crop("160x640+#{i * 160}+0")
      @image.write "app/assets/images/cilindro" + i.to_s() + ".png"
    end

    #JUNTA AS FATIAS DAS DUAS IMAGENS NUMA NOVA E GUARDA-A NO DISCO
    @nomedaimagem = rand.to_s
    image_list = Magick::ImageList.new( "app/assets/images/cone0.png", "app/assets/images/cilindro0.png", "app/assets/images/cone1.png", "app/assets/images/cilindro1.png", "app/assets/images/cone2.png", "app/assets/images/cilindro2.png", "app/assets/images/cone3.png", "app/assets/images/cilindro3.png" )
    image_list.append(false).write("app/assets/images/images.png")
    Cloudinary::Uploader.upload("app/assets/images/images.png", :public_id => "#{@nomedaimagem}", :folder => "finais", :invalidate => true)

  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:nome, :urldoinsta, :slyce, :remote_slyce_url)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">  
    <%= f.label :remote_slyce_url, "" %>  
    <%= f.text_field :remote_slyce_url %>  
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/busca.html.erb
<!-- isto serve para encontrar o user id a partir do username -->
<!-- <div>
<p class="h1">busca de fotos do user, tem de usar aindo o userid</p>
	<%= form_tag({controller: "pins", action: "perfil", method: "post"}) do %>
	  <%= label_tag(:q, "Search for:") %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	<% end %>
</div> -->
 
<!-- isto serve para mostrar as ultimas 10 fotos do user -->
<!--  <p>busca de fotos do user</p>
	<%= form_tag({controller: "pins", action: "index", method: "post"}) do %>
	  <%= label_tag(:q, "Search for:") %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	<% end %>  -->

<h1>Abre o <%= link_to 'instagram', "http://instagram.com", :target => "_blank" %> e copia o link de duas fotos que gostes muito para os campos abaixo</h1>
<h2>(ainda não funciona com contas privadas, em breve...)</h2>

</br>
</br>
</br>

<div>	
	<%= form_tag({controller: "pins", action: "fromlink", method: "get"}) do %>
	<%= label_tag(:q, "Link da primeira foto:") %>
	<%= text_field_tag(:q) %>
	<%= label_tag(:p, "Link da segunda foto:") %>
	<%= text_field_tag(:p) %>
	<%= submit_tag("Fazer magia") %>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/fromlink.html.erb
  
<h2>"MAGIA? Não estou a ver magia nenhuma!"</h2>
<h2>Experimenta clicar num dos botões por debaixo da imagem!</h2>
  <div class= "paper"> 
    <div class="overlay">
    
    </div>
  </div>


<button id="button" onclick="exemplo.stairs(44, 'left');">vista da esquerda</button>

<button id="button" onclick="exemplo.accordion(-45);">vista do centro</button>

<button id="button" onclick="exemplo.stairs(45, 'right')">vista da direita</button>

<!-- 
<%= cl_image_tag("finais/#{@nomedaimagem}.png", :alt => "imagem") %>

 -->

<style >
  .overlay { 
  	background: url("<%= cloudinary_url("finais/#{@nomedaimagem}.png", :resource_type => :image) %>");
  }
</style>



<script>
	var exemplo = new OriDomi('.paper', {
		speed:           3000,  
		ripple:          4,     // backwards ripple effect when animating
		perspective:     5000,   // smaller values exaggerate 3D distortion
		maxAngle:        180,    //fold range
		vPanels:         8, 
		hPanels:         1, 
		shading:         'soft', 
		touchEnabled:    true, 
		touchSensitivity: .10
	});
	

</script>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/oridomi.html.erb
<style >
  .overlay { 
  	background: url("<%= cloudinary_url("finais/0.9063961155570877.png", :resource_type => :image) %>");
  }
</style>

  <div class= "row-fluid paper"> 
    <div class="overlay">
    
    </div>
  </div>

<button id="button" onclick="exemplo.stairs(43, 'left');">vista da esquerda</button>

<button id="button" onclick="exemplo.accordion(-48);">vista do centro</button>

<button id="button" onclick="exemplo.stairs(43, 'right')">vista da direita</button>


<script>
	var exemplo = new OriDomi('.paper', {
		speed:           2000,  
		ripple:          3,     // backwards ripple effect when animating
		perspective:     3000,   // smaller values exaggerate 3D distortion
		maxAngle:        360,    //fold range
		vPanels:         8, 
		hPanels:         1, 
		shading:         'soft', 
		touchEnabled:    true, 
		touchSensitivity: .10
	});
</script>

app/views/pins/perfil.html.erb
<% @instagram.each do |instagram| %>

<%= image_tag instagram.profile_picture %>
<%= image_tag instagram.user_recent_media(instagram.id) %>
<p class="h1"><%= instagram.id %></p>

<% end %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag @pin.slyce_url.to_s %>  
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>